# Copyright (c) 2019-2025 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

jobs:
  - job: check_codespell
    displayName: "codespell"
    pool:
      vmImage: "ubuntu-latest"
    container: khronosgroup/docker-images:openxr-sdk.20240924@sha256:5e6a6f5d72dc4a20d5c33f12550fdd9b6a1206e94d6cf1382e0697a5726c424c

    steps:
      - checkout: self
        lfs: true

      - script: ./checkCodespell
        displayName: Run Codespell script
